# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMhiDgL5B5ZFzGREhv1iikho47O6Qu7W
"""

import pandas as pd

# Load the new CSV file
df = pd.read_csv('/content/drive/MyDrive/Data Analysis/householdtask3.csv', encoding='latin1')

df.head()

import matplotlib.pyplot as plt

# Create a bar chart for total households by year
plt.figure(figsize=(14, 6))

# Bar chart for total households
plt.subplot(1, 2, 1)
df.groupby('ï»¿year')['tot_hhs'].sum().plot(kind='bar', color='skyblue')
plt.title('Total Households by Year')
plt.xlabel('Year')
plt.ylabel('Total Households')
plt.xticks(rotation=45)
plt.legend(['Total Households'])

# Line chart for average income by year
plt.subplot(1, 2, 2)
df.groupby('ï»¿year')['income'].mean().plot(kind='line', marker='o', color='orange')
plt.title('Average Income by Year')
plt.xlabel('Year')
plt.ylabel('Average Income')
plt.xticks(rotation=45)
plt.legend(['Average Income'])

# Adjust layout
plt.tight_layout()
plt.show()

plt.hist(df['income'], bins=20, color='skyblue', edgecolor='black')
plt.title('Income Distribution')
plt.xlabel('Income')
plt.ylabel('Frequency')
plt.show()

plt.scatter(df['income'], df['expenditure'], color='orange', alpha=0.5)
plt.title('Income vs Expenditure')
plt.xlabel('Income')
plt.ylabel('Expenditure')
plt.show()

